// This file will be auto-generated by Supabase CLI
// For now, we'll create a placeholder that extends our Prisma types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string;
          first_name: string;
          last_name: string;
          role: 'ADMIN' | 'MANAGER' | 'USER' | 'WAREHOUSE' | 'SALES';
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
          organization_id: string | null;
        };
        Insert: Omit<
          Database['public']['Tables']['users']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: 'free' | 'pro' | 'enterprise';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['organizations']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
      };
      items: {
        Row: {
          id: string;
          sku: string;
          upc: string | null;
          name: string;
          description: string | null;
          category_id: string;
          uom_id: string;
          default_supplier_id: string | null;
          default_cost: number | null;
          default_price: number | null;
          weight_kg: number | null;
          length_cm: number | null;
          width_cm: number | null;
          height_cm: number | null;
          reorder_point: number;
          reorder_qty: number;
          is_active: boolean;
          organization_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['items']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['items']['Insert']>;
      };
      inventory: {
        Row: {
          id: string;
          item_id: string;
          lot_id: string | null;
          serial_id: string | null;
          location_id: string;
          qty_on_hand: number;
          qty_reserved: number;
          qty_in_transit: number;
          last_counted_at: string | null;
          organization_id: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['inventory']['Row'], 'id' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['inventory']['Insert']>;
      };
      stock_movements: {
        Row: {
          id: string;
          item_id: string;
          lot_id: string | null;
          serial_id: string | null;
          from_location_id: string | null;
          to_location_id: string | null;
          qty: number;
          movement_type:
            | 'INBOUND'
            | 'OUTBOUND'
            | 'TRANSFER'
            | 'ADJUSTMENT'
            | 'RETURN'
            | 'DAMAGE'
            | 'LOSS';
          ref_type: string | null;
          ref_id: string | null;
          moved_by_id: string;
          moved_at: string;
          notes: string | null;
          organization_id: string;
        };
        Insert: Omit<Database['public']['Tables']['stock_movements']['Row'], 'id' | 'moved_at'>;
        Update: Partial<Database['public']['Tables']['stock_movements']['Insert']>;
      };
    };
    Views: {
      inventory_summary: {
        Row: {
          item_id: string;
          item_name: string;
          sku: string;
          total_on_hand: number;
          total_reserved: number;
          total_available: number;
          location_count: number;
          organization_id: string;
        };
      };
    };
    Functions: {
      calculate_available_stock: {
        Args: { p_item_id: string };
        Returns: number;
      };
      adjust_stock: {
        Args: {
          p_item_id: string;
          p_location_id: string;
          p_qty_change: number;
          p_reason: string;
          p_user_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: 'ADMIN' | 'MANAGER' | 'USER' | 'WAREHOUSE' | 'SALES';
      movement_type:
        | 'INBOUND'
        | 'OUTBOUND'
        | 'TRANSFER'
        | 'ADJUSTMENT'
        | 'RETURN'
        | 'DAMAGE'
        | 'LOSS';
      organization_plan: 'free' | 'pro' | 'enterprise';
    };
  };
}
