// This file will be auto-generated by Supabase CLI
// For now, we'll use a placeholder type
export type Database = {
  public: {
    Tables: {
      // This will be populated with your actual database schema
      [key: string]: unknown;
    };
    Views: {
      [key: string]: unknown;
    };
    Functions: {
      [key: string]: unknown;
    };
    Enums: {
      [key: string]: unknown;
    };
  };
};